# Generated by Django 3.0 on 2021-12-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_category', models.CharField(choices=[('sports', 'sports'), ('collection', 'collection'), ('racingboots', 'racingboots')], max_length=100)),
                ('shoes_name', models.CharField(max_length=100)),
                ('shoes_price', models.IntegerField()),
                ('shoes_quantity', models.IntegerField()),
                ('shoes_image', models.ImageField(upload_to='shoes_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
